100 event title component
202212-GIZ-YE-FEW/Web_Wizards_Pebble pull request #103
Opened 2023-04-15 11:58 UTC by sulmi24

1. This pull request adds the EventTitle component to the project. 
2. The EventTitle component is used to render a text input element with a placeholder text, border, and shadow.
![image](https://user-images.githubusercontent.com/82319372/232218959-3c33de35-b62d-4219-ae7f-c3099bc8d0f2.png)

2023-04-15 14:03 UTC, SufyanCS approved these changes
Good to go

2023-04-15 15:32 UTC, iiAbady requested changes
This needs to support both language English and Arabic and it's good to go.

2023-04-16 14:50 UTC, sulmi24 commented
> This needs to support both language English and Arabic and it's good to go.

Working on it after I finsh the page

2023-04-16 15:35 UTC, iiAbady approved these changes

2023-04-16 19:30 UTC, merged