fix: navbar and auth
202212-GIZ-YE-FEW/Web_Wizards_Pebble pull request #115
Opened 2023-04-24 05:24 UTC by iiAbady

## **Describe what does this pull request do?**

This pull request fixes current issues and bugs in the navbar and authentication system and these includes but not limited to:

- No translation for some of navigations.
- Incorrect styling for some components.
- Authentication Error Box components yielding bugs.
- Missing navigations for mobile users.

2023-04-24 08:31 UTC, SufyanCS requested changes
Great job, @iiAbady I noticed a few issues that I think could be improved:
Firstly, when I try to add special characters to my password, it doesn't allow me to, could you make this an optional feature so that users can choose whether or not to include special characters?

Secondly, the alert message could be improved. It would be helpful to have a better design and the ability to dismiss the alert with an "x" button (You can find one in tailwind coponents).

 after creating an account and attempting to log in, the spinner moves and stops but doesn't redirect me to the home page or show that I am logged in until I refresh the page

Finally, it would be great if you could add the spinner inside the button.
Thank you for your hard work!

2023-04-24 10:58 UTC, sulmi24 approved these changes

2023-04-26 08:47 UTC, SufyanCS approved these changes

2023-04-26 10:25 UTC, Adeeb2022 approved these changes
cool

2023-04-27 17:32 UTC, merged